# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.
fib = fib_1 = fib_2 = sum = 0

while fib < 4_000_000
  # puts fib  
  fib = (fib == 0) ? 1 : fib_1 + fib_2
  fib_2 = fib_1
  fib_1 = fib
  sum = sum + fib if fib % 2 == 0
end

puts sum
