Feature: Project Euler - Problem 2
  Each new term in the Fibonacci sequence is generated by adding the previous 
  two terms. By starting with 1 and 2, the first 10 terms will be:
  
  0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  By considering the terms in the Fibonacci sequence whose values do not exceed 
  four million, find the sum of the even-valued terms.

Scenario: Sum of even Fibonacci numbers less than 4,000,000
  Given the Fibonacci numbers are less than 4000000
  When the numbers to sum are even
  Then the sum numbers is 4613732
